#!/usr/bin/env bash
# =============================================================================
#  backend_only_ec2.sh
#  Paste this ENTIRE script into the EC2 Instance Connect terminal.
#  Deploys ONLY the Flask backend. No Docker. No Node. No ML models.
#  Disk usage: ~300 MB total (vs 5+ GB for full stack)
# =============================================================================
set -euo pipefail

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  AI Interview System — Backend-Only EC2 Deployment"
echo "  Target: Flask + Gunicorn on Ubuntu · t3.micro"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Collect secrets ───────────────────────────────────────────────────────────
read -rsp ">> Enter your GEMINI_API_KEY (required): " GEMINI_API_KEY; echo
[[ -z "$GEMINI_API_KEY" ]] && { echo "GEMINI_API_KEY cannot be empty."; exit 1; }
JWT_SECRET=$(openssl rand -hex 32)
SECRET_KEY=$(openssl rand -hex 32)
echo "✔ Secrets ready."

# ── Step 1: Swap (critical for 1 GB RAM) ─────────────────────────────────────
echo ""
echo "[1/8] Enabling 2 GB swap..."
if [[ ! -f /swapfile ]]; then
  sudo fallocate -l 2G /swapfile
  sudo chmod 600 /swapfile
  sudo mkswap /swapfile
  sudo swapon /swapfile
  echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null
  sudo sysctl vm.swappiness=10
  echo 'vm.swappiness=10' | sudo tee -a /etc/sysctl.conf > /dev/null
  echo "✔ 2 GB swap active: $(free -h | grep Swap)"
else
  echo "✔ Swap already configured."
fi

# ── Step 2: System packages (Python only — no Node/Docker) ───────────────────
echo ""
echo "[2/8] Installing system packages..."
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update -yq 2>/dev/null
sudo apt-get install -yq \
  git curl wget \
  python3 python3-pip python3-venv python3-dev python3-wheel \
  build-essential libssl-dev libffi-dev libpq-dev \
  nginx ufw \
  ca-certificates 2>/dev/null
echo "✔ System packages installed."

# ── Step 3: Clone / pull repository ──────────────────────────────────────────
echo ""
echo "[3/8] Cloning repository..."
APP_DIR="/opt/ai-interview-system"
if [[ -d "$APP_DIR/.git" ]]; then
  echo "  → Repo exists, pulling latest..."
  sudo git -C "$APP_DIR" fetch --all
  sudo git -C "$APP_DIR" reset --hard origin/main 2>/dev/null || \
  sudo git -C "$APP_DIR" reset --hard origin/master 2>/dev/null || true
else
  sudo git clone https://github.com/manikanta-devs/mca-final-project.git "$APP_DIR"
fi
sudo chown -R ubuntu:ubuntu "$APP_DIR"
echo "✔ Repo at $APP_DIR"

# ── Step 4: Python venv + lean requirements ───────────────────────────────────
echo ""
echo "[4/8] Setting up Python environment..."
cd "$APP_DIR/backend"

# Create a lean requirements file that skips heavy ML packages
# (SadTalker, Wav2Lip, heavy torch deps — not needed for the core API)
cat > /tmp/requirements_lean.txt <<'LEAN'
# Core Flask
flask==3.0.2
flask-cors==4.0.0
flask-limiter==3.5.0
Werkzeug==3.0.1

# Environment
python-dotenv==1.0.1

# Auth
PyJWT==2.13.0

# AI providers
google-generativeai==0.8.3
requests==2.31.0

# NLP & resume parsing (lightweight)
spacy==3.7.4
PyPDF2==3.0.1
python-docx==1.1.0

# Data validation
pydantic==2.5.0

# WSGI
gunicorn==21.2.0

# Monitoring
psutil==5.9.8
LEAN

python3 -m venv .venv
source .venv/bin/activate

pip install --upgrade pip --quiet

# Try lean requirements first; fall back to full requirements.txt if it fails
if pip install -r /tmp/requirements_lean.txt --quiet 2>/dev/null; then
  echo "✔ Lean requirements installed."
else
  echo "  → Lean install failed, trying requirements.txt..."
  pip install -r requirements.txt --quiet || {
    echo "  → requirements.txt failed, installing core packages only..."
    pip install flask flask-cors python-dotenv PyJWT google-generativeai \
      requests PyPDF2 python-docx pydantic gunicorn psutil flask-limiter --quiet
  }
fi

# Install spaCy English model (small = ~12 MB only)
echo "  → Installing spaCy en_core_web_sm (~12 MB)..."
python3 -m spacy download en_core_web_sm --quiet 2>/dev/null || \
  echo "  ! spaCy model install skipped (non-fatal)."

deactivate
echo "✔ Python environment ready."

# ── Step 5: Write .env ────────────────────────────────────────────────────────
echo ""
echo "[5/8] Writing environment configuration..."

# Detect if frontend will be on Vercel/Netlify (CORS must allow it)
# We set ALLOWED_ORIGINS=* for now; tighten after Vercel URL is known
cat > "$APP_DIR/backend/.env" <<ENV
# ── Auto-generated by backend_only_ec2.sh ──
FLASK_ENV=production
FLASK_DEBUG=0
DEBUG=false

# Secrets
SECRET_KEY=${SECRET_KEY}
JWT_SECRET=${JWT_SECRET}

# AI
GEMINI_API_KEY=${GEMINI_API_KEY}
LOCAL_LLM_ENABLED=false

# CORS — allow all origins (tighten after Vercel deploy)
ALLOWED_ORIGINS=*

# Rate limiting
RATE_LIMIT_ENABLED=true

# App
MAX_QUESTIONS=10
MIN_QUESTIONS=3
SESSION_TIMEOUT_HOURS=24
LOG_LEVEL=INFO

# Port
PORT=5000
ENV
chmod 600 "$APP_DIR/backend/.env"

# Create uploads directory
mkdir -p "$APP_DIR/backend/uploads"
chown ubuntu:ubuntu "$APP_DIR/backend/uploads"
echo "✔ .env written."

# ── Step 6: Detect Flask entry point & create systemd service ─────────────────
echo ""
echo "[6/8] Creating systemd service..."

FLASK_ENTRY="app.py"
for f in app.py main.py run.py wsgi.py; do
  [[ -f "$APP_DIR/backend/$f" ]] && { FLASK_ENTRY="$f"; break; }
done
FLASK_MODULE="${FLASK_ENTRY%.py}:app"
echo "  → Entry point: $FLASK_MODULE"

# Use gunicorn.conf.py if present, otherwise build flags manually
GUNICORN_CONF=""
[[ -f "$APP_DIR/backend/gunicorn.conf.py" ]] && GUNICORN_CONF="--config $APP_DIR/backend/gunicorn.conf.py"

sudo tee /etc/systemd/system/ai-interview-backend.service > /dev/null <<UNIT
[Unit]
Description=AI Interview System — Flask/Gunicorn Backend
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
User=ubuntu
Group=ubuntu
WorkingDirectory=${APP_DIR}/backend
EnvironmentFile=${APP_DIR}/backend/.env

ExecStart=${APP_DIR}/backend/.venv/bin/gunicorn \\
    ${GUNICORN_CONF} \\
    --bind 127.0.0.1:5000 \\
    --workers 2 \\
    --threads 2 \\
    --worker-class gthread \\
    --timeout 120 \\
    --keep-alive 5 \\
    --access-logfile /var/log/ai-backend-access.log \\
    --error-logfile  /var/log/ai-backend-error.log \\
    --capture-output \\
    ${FLASK_MODULE}

ExecReload=/bin/kill -s HUP \$MAINPID
KillMode=mixed
TimeoutStopSec=10
PrivateTmp=true
Restart=on-failure
RestartSec=5
StartLimitIntervalSec=60
StartLimitBurst=3

[Install]
WantedBy=multi-user.target
UNIT

sudo touch /var/log/ai-backend-access.log /var/log/ai-backend-error.log
sudo chown ubuntu:ubuntu /var/log/ai-backend-access.log /var/log/ai-backend-error.log

sudo systemctl daemon-reload
sudo systemctl enable ai-interview-backend
sudo systemctl restart ai-interview-backend
echo "✔ Backend service started."

# Wait for backend to come up
echo "  → Waiting for backend to start..."
for i in {1..15}; do
  if curl -sf http://127.0.0.1:5000/health &>/dev/null || \
     curl -sf http://127.0.0.1:5000/ &>/dev/null; then
    echo "  ✔ Backend is responding on :5000"
    break
  fi
  sleep 2
done

# ── Step 7: Nginx — API only (no static files) ────────────────────────────────
echo ""
echo "[7/8] Configuring Nginx reverse proxy..."

sudo tee /etc/nginx/sites-available/ai-interview > /dev/null <<'NGINX'
# AI Interview System — Backend-only Nginx config
# Frontend is deployed separately on Vercel/Netlify

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # Upload size limit (resume PDFs)
    client_max_body_size 20M;

    # Security headers
    add_header X-Content-Type-Options "nosniff"     always;
    add_header X-Frame-Options        "SAMEORIGIN"  always;
    add_header X-XSS-Protection       "1; mode=block" always;

    # CORS pre-flight handled by Flask-CORS
    # Nginx just proxies everything through

    # ── Health check (no auth needed) ───────────────────────────────────
    location = /health {
        proxy_pass http://127.0.0.1:5000/health;
        proxy_set_header Host $host;
        access_log off;
    }

    # ── All API traffic ─────────────────────────────────────────────────
    location /api/ {
        proxy_pass         http://127.0.0.1:5000/api/;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";
        proxy_read_timeout    120s;
        proxy_connect_timeout  10s;
        proxy_send_timeout    120s;
    }

    # ── Uploaded files (resume storage) ─────────────────────────────────
    location /uploads/ {
        alias /opt/ai-interview-system/backend/uploads/;
        internal;
    }

    # ── Root: simple status page so the IP shows something ──────────────
    location / {
        proxy_pass http://127.0.0.1:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
NGINX

sudo ln -sf /etc/nginx/sites-available/ai-interview \
            /etc/nginx/sites-enabled/ai-interview
sudo rm -f /etc/nginx/sites-enabled/default

sudo nginx -t
sudo systemctl enable nginx
sudo systemctl reload nginx
echo "✔ Nginx configured."

# ── Step 8: Firewall ──────────────────────────────────────────────────────────
echo ""
echo "[8/8] Configuring firewall..."
sudo ufw --force reset > /dev/null
sudo ufw default deny incoming > /dev/null
sudo ufw default allow outgoing > /dev/null
sudo ufw allow 22/tcp  comment 'SSH'   > /dev/null
sudo ufw allow 80/tcp  comment 'HTTP'  > /dev/null
sudo ufw allow 443/tcp comment 'HTTPS' > /dev/null
sudo ufw --force enable > /dev/null
echo "✔ Firewall: ports 22, 80, 443 open."

# ── Validation ────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  VALIDATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
check_url() {
  local desc="$1" url="$2"
  local code
  code=$(curl -so /dev/null -w "%{http_code}" --max-time 8 "$url" 2>/dev/null || echo "000")
  if [[ "$code" =~ ^(200|301|302|401|405|422)$ ]]; then
    echo "  ✔  $desc → HTTP $code"
  else
    echo "  ✘  $desc → HTTP $code"
  fi
}
sleep 5
check_url "Backend /health"          "http://127.0.0.1/health"
check_url "Backend /api/health"      "http://127.0.0.1/api/health"
check_url "Interview generate route" "http://127.0.0.1/api/interview/generate"
check_url "Resume parse route"       "http://127.0.0.1/api/resume/parse"

# ── Memory report ─────────────────────────────────────────────────────────────
echo ""
echo "  Memory usage:"
free -h | grep -E "Mem|Swap"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  BACKEND DEPLOYMENT COMPLETE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  API Base URL : http://18.61.78.226/api"
echo "  Health check : http://18.61.78.226/health"
echo ""
echo "  NEXT STEP — Deploy frontend to Vercel (free):"
echo "  1. Push code to GitHub"
echo "  2. Go to vercel.com → Import your repo"
echo "  3. Set env var: VITE_API_URL=http://18.61.78.226/api"
echo "  4. Deploy → done!"
echo ""
echo "  Useful commands:"
echo "  Backend status : sudo systemctl status ai-interview-backend"
echo "  Backend logs   : sudo journalctl -u ai-interview-backend -f"
echo "  Nginx logs     : sudo journalctl -u nginx -f"
echo "  Restart        : sudo systemctl restart ai-interview-backend"
echo "  Disk usage     : df -h / && du -sh /opt/ai-interview-system"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
